In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/word2vec_dataset.csv')

In [3]:
df.head()

,Unnamed: 0,title,text,label,w2v_0,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,...,w2v_90,w2v_91,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99
0,0,LAW ENFORCEMENT HIGH ALERT Following Threats C...,comment expected Barack Obama Members FYF911 F...,1,-0.153850,0.166630,0.012184,0.002717,-0.005172,-0.439930,...,0.264924,-0.009136,-0.090765,-0.079516,0.352408,0.046338,0.144641,-0.218678,-0.049368,-0.080279
1,1,NaN,post vote Hillary already,1,-0.170780,0.310585,0.257455,-0.254393,0.161752,-0.573075,...,0.380012,0.258434,-0.160533,-0.278399,0.432094,0.015994,0.086608,-0.201986,-0.265015,-0.137781
2,2,UNBELIEVABLE OBAMAS ATTORNEY GENERAL SAYS CHAR...,demonstrator gathered last night exercising co...,1,-0.136740,0.256605,0.040868,-0.031231,-0.053745,-0.428697,...,0.360347,0.026897,-0.198899,0.046315,0.364352,-0.055555,0.198040,-0.363083,0.138671,-0.136357
3,3,Bobby Jindal raised Hindu us story Christian c...,dozen politically active pastor came private d...,0,-0.112406,0.162305,0.133007,0.113505,-0.150368,-0.596209,...,0.286252,0.018290,-0.039149,-0.014438,0.370662,-0.050437,0.103233,-0.200700,-0.095522,-0.111361
4,4,SATAN 2 Russia unvelis image terrifying new SU...,RS28 Sarmat missile dubbed Satan 2 replace SS1...,1,-0.115462,0.162735,0.098371,-0.127138,-0.018668,-0.406562,...,0.282940,-0.023499,0.081211,-0.129009,0.343502,-0.088082,0.301875,-0.280927,-0.019663,-0.150571

In [4]:
df_x = df.drop(columns=['Unnamed: 0', 'title', 'text', 'label'])
df_y = df['label']

In [6]:
df_x.to_csv('../data/processed_word2vec.csv', index=False)
df_y.to_csv('../data/processed_label.csv', index=False)

In [7]:
df_x.head()

,w2v_0,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,...,w2v_90,w2v_91,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99
0,-0.153850,0.166630,0.012184,0.002717,-0.005172,-0.439930,0.177939,0.485429,-0.106813,-0.180510,...,0.264924,-0.009136,-0.090765,-0.079516,0.352408,0.046338,0.144641,-0.218678,-0.049368,-0.080279
1,-0.170780,0.310585,0.257455,-0.254393,0.161752,-0.573075,0.243773,0.364087,-0.135016,-0.220500,...,0.380012,0.258434,-0.160533,-0.278399,0.432094,0.015994,0.086608,-0.201986,-0.265015,-0.137781
2,-0.136740,0.256605,0.040868,-0.031231,-0.053745,-0.428697,0.221130,0.678414,-0.117271,-0.190190,...,0.360347,0.026897,-0.198899,0.046315,0.364352,-0.055555,0.198040,-0.363083,0.138671,-0.136357
3,-0.112406,0.162305,0.133007,0.113505,-0.150368,-0.596209,0.245951,0.566223,-0.173389,-0.194219,...,0.286252,0.018290,-0.039149,-0.014438,0.370662,-0.050437,0.103233,-0.200700,-0.095522,-0.111361
4,-0.115462,0.162735,0.098371,-0.127138,-0.018668,-0.406562,0.261808,0.535396,-0.105081,-0.233351,...,0.282940,-0.023499,0.081211,-0.129009,0.343502,-0.088082,0.301875,-0.280927,-0.019663,-0.150571

In [8]:
df_y.head()

0    1
1    1
2    1
3    0
4    1
Name: label, dtype: int64