In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df = pd.read_csv('nopunct_nostopwords.csv')

In [6]:
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT HIGH ALERT Following Threats C...,comment expected Barack Obama Members FYF911 F...,1
1,1,NaN,post votes Hillary already,1
2,2,UNBELIEVABLE OBAMAS ATTORNEY GENERAL SAYS CHAR...,demonstrators gathered last night exercising c...,1
3,3,Bobby Jindal raised Hindu uses story Christian...,dozen politically active pastors came private ...,0
4,4,SATAN 2 Russia unvelis image terrifying new SU...,RS28 Sarmat missile dubbed Satan 2 replace SS1...,1

In [8]:
vectorizer = TfidfVectorizer(
    max_features=2000,    
    ngram_range=(1, 2),
    stop_words='english'
)

In [14]:
df['text'] = df['text'].fillna('')
tfidf_matrix = vectorizer.fit_transform(df['text'])

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)
df_tfidf = pd.concat([df.reset_index(drop=True), tfidf_df.reset_index(drop=True)], axis=1)

df_tfidf = df_tfidf.drop(columns=['title', 'text'])

In [15]:
df_tfidf.to_csv('tfidf_dataset.csv', index=False)
df_tfidf.head()

,Unnamed: 0,label,000,10,100,11,12,13,14,15,...,yemen,yes,york,york city,york times,young,youre,youtube,zero,zone
0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.037472,0.0,0.051148,0.0,0.0
1,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
2,2,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
3,3,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.033572,0.0,0.000000,0.0,0.0
4,4,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0