In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
df = pd.read_csv('data/lemmatized.csv')
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT HIGH ALERT Following Threats C...,comment expected Barack Obama Members FYF911 F...,1
1,1,NaN,post vote Hillary already,1
2,2,UNBELIEVABLE OBAMAS ATTORNEY GENERAL SAYS CHAR...,demonstrator gathered last night exercising co...,1
3,3,Bobby Jindal raised Hindu us story Christian c...,dozen politically active pastor came private d...,0
4,4,SATAN 2 Russia unvelis image terrifying new SU...,RS28 Sarmat missile dubbed Satan 2 replace SS1...,1

In [4]:
vectorizer = TfidfVectorizer(
    max_features=2000,    
    ngram_range=(1, 2),
    stop_words='english'
)

In [8]:
df['text'] = df['text'].fillna('')
tfidf_matrix = vectorizer.fit_transform(df['text'])

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)
df_tfidf = pd.concat([df.reset_index(drop=True), tfidf_df.reset_index(drop=True)], axis=1)

df_tfidf = df_tfidf.drop(columns=['Unnamed: 0', 'title', 'text', 'label'])

In [9]:
df_tfidf.to_csv('data/tfidf_dataset.csv', index=False)
df_tfidf.head()

,000,10,100,11,12,13,14,15,16,17,...,yes,yesterday,york,york city,york times,young,youre,youtube,zero,zone
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.036255,0.0,0.049488,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.032240,0.0,0.000000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.073491,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0